package com.stateai.domain.features

import com.stateai.domain.sensing.SensorSample
import java.io.File
import java.time.Instant
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource

/**
 * Kotlin and Python must compute the same features. Both are tested against the shared cases in
 * `shared/parity/feature_cases.json` (generated by `python -m stateai_ml.parity`).
 */
class FeatureParityTest {
    @ParameterizedTest(name = "{0}")
    @MethodSource("cases")
    fun `matches the shared parity case`(name: String, case: JsonObject) {
        val start = Instant.parse("2026-10-04T09:00:00Z")
        val heartRates = case.getValue("heart_rates").jsonArray
        val movements = case.getValue("movements").jsonArray
        val samples = heartRates.indices.map { index ->
            SensorSample(start.plusSeconds(index.toLong()), heartRates[index].doubleOrNull(), movements[index].double())
        }

        val window = FeatureExtractor().extract(samples)!!
        val expected = case.getValue("expected").jsonObject

        assertEquals(expected.int("sample_count"), window.sampleCount, name)
        assertEquals(expected.int("heart_rate_count"), window.heartRateCount, name)
        assertEquals(expected.int("fidget_count"), window.fidgetCount, name)
        assertClose(expected.getValue("mean_heart_rate").doubleOrNull(), window.meanHeartRate)
        assertClose(expected.getValue("heart_rate_std_dev").double(), window.heartRateStdDev)
        assertClose(expected.getValue("heart_rate_mean_abs_diff").double(), window.heartRateMeanAbsDiff)
        assertClose(expected.getValue("mean_movement").double(), window.meanMovement)
        assertClose(expected.getValue("high_movement_share").double(), window.highMovementShare)
    }

    private fun assertClose(expected: Double?, actual: Double?) {
        if (expected == null) return assertNull(actual)
        assertEquals(expected, actual!!, TOLERANCE)
    }

    private fun JsonObject.int(key: String) = getValue(key).jsonPrimitive.content.toInt()

    private fun JsonElement.double() = jsonPrimitive.content.toDouble()

    private fun JsonElement.doubleOrNull() = if (this is JsonNull) null else double()

    companion object {
        private const val TOLERANCE = 1e-9
        private val CASES_FILE = File("../shared/parity/feature_cases.json")

        @JvmStatic
        fun cases(): List<Array<Any>> = Json.parseToJsonElement(CASES_FILE.readText()).jsonArray.map { case ->
            arrayOf(case.jsonObject.getValue("name").jsonPrimitive.content, case.jsonObject)
        }
    }
}
