package com.stateai.domain.state.model

import com.stateai.domain.baseline.UserBaseline
import com.stateai.domain.features.FeatureExtractor
import com.stateai.domain.sensing.SensorSample
import java.io.File
import java.time.Instant
import kotlin.math.abs
import kotlin.time.Duration.Companion.minutes
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource

/**
 * From the same raw window, Kotlin must build the same model inputs as Python. Cases come from
 * `shared/parity/prediction_cases.json` (generated by `python -m stateai_ml.prediction_parity`); the
 * TFLite probabilities for those inputs are checked on the emulator in `:ml`.
 */
class ModelInputsParityTest {
    @ParameterizedTest(name = "{0}")
    @MethodSource("cases")
    fun `matches the shared prediction case`(name: String, case: JsonObject) {
        val window = FeatureExtractor().extract(samples(windows.getValue(case.text("window"))))!!
        val baseline = UserBaseline(case.number("resting_heart_rate"), 1.0, Instant.EPOCH)

        val inputs = ModelInputs.of(window, baseline, case.number("elapsed_minutes").minutes)!!

        val expected = case.getValue("inputs").jsonArray.map { it.double() }
        expected.forEachIndexed { index, value ->
            assertEquals(value, inputs[index].toDouble(), TOLERANCE * maxOf(1.0, abs(value)), name)
        }
    }

    private fun samples(window: JsonObject): List<SensorSample> {
        val start = Instant.parse("2026-10-04T09:00:00Z")
        val heartRates = window.getValue("heart_rates").jsonArray
        val movements = window.getValue("movements").jsonArray
        return heartRates.indices.map { index ->
            SensorSample(start.plusSeconds(index.toLong()), heartRates[index].doubleOrNull(), movements[index].double())
        }
    }

    private fun JsonObject.text(key: String) = getValue(key).jsonPrimitive.content

    private fun JsonObject.number(key: String) = getValue(key).double()

    private fun JsonElement.double() = jsonPrimitive.content.toDouble()

    private fun JsonElement.doubleOrNull() = if (this is JsonNull) null else double()

    companion object {
        /** Inputs are floats, so the match is relative to float precision. */
        private const val TOLERANCE = 1e-6

        private val windows = Json.parseToJsonElement(File("../shared/parity/feature_cases.json").readText())
            .jsonArray.associate { it.jsonObject.getValue("name").jsonPrimitive.content to it.jsonObject }

        @JvmStatic
        fun cases(): List<Array<Any>> =
            Json.parseToJsonElement(File("../shared/parity/prediction_cases.json").readText()).jsonArray.map {
                arrayOf(it.jsonObject.getValue("name").jsonPrimitive.content, it.jsonObject)
            }
    }
}
