"""Markdown report of the classifier comparison."""

from dataclasses import dataclass

import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

from stateai_ml.model import CLASSES, INPUT_COLUMNS


@dataclass(frozen=True)
class Scores:
    accuracy: float
    macro_f1: float
    confusion: list

    @staticmethod
    def of(truth, predicted) -> "Scores":
        return Scores(
            accuracy=accuracy_score(truth, predicted),
            macro_f1=f1_score(truth, predicted, labels=CLASSES, average="macro"),
            confusion=confusion_matrix(truth, predicted, labels=CLASSES).tolist(),
        )


@dataclass(frozen=True)
class Comparison:
    train_users: list[str]
    test_users: list[str]
    train_windows: int
    test: pd.DataFrame
    rules: Scores
    rules_true_baseline: Scores
    model: Scores
    true_resting: dict[str, float]


def render(comparison: Comparison) -> str:
    return "\n".join(
        [
            _header(comparison),
            _results(comparison),
            "## Rule engine (calibrated baseline)\n",
            _confusion(comparison.rules.confusion),
            "\n## Logistic regression\n",
            _confusion(comparison.model.confusion),
            _diagnosis(comparison),
            _reading(comparison),
        ]
    )


def _header(c: Comparison) -> str:
    inputs = ", ".join(f"`{column}`" for column in INPUT_COLUMNS)
    return f"""# State classifier report

Generated by `python -m stateai_ml.evaluate_classifier`. **All data is synthetic** (see
`src/stateai_ml/synthetic/README.md`); nothing here measures accuracy on real people.

- Model: standardized inputs ({inputs}) into a multinomial logistic regression, trained on
  {c.train_windows} clean windows of users {", ".join(c.train_users)}.
- Test: {len(c.test)} clean windows of held-out users {", ".join(c.test_users)}.
- Truth: the generator's latent level (majority over the window), which the watch never sees.
"""


def _results(c: Comparison) -> str:
    rows = [
        ("Rule engine, baseline from the 2-minute calibration (as on the watch)", c.rules),
        ("Rule engine, true resting heart rate (oracle)", c.rules_true_baseline),
        ("Logistic regression", c.model),
    ]
    table = "\n".join(f"| {name} | {s.accuracy:.3f} | {s.macro_f1:.3f} |" for name, s in rows)
    return f"| Classifier | Accuracy | Macro F1 |\n|---|---|---|\n{table}\n"


def _confusion(matrix: list) -> str:
    header = "| true \\ predicted | " + " | ".join(CLASSES) + " |\n|---|" + "---|" * len(CLASSES)
    rows = [f"| {label} | " + " | ".join(map(str, row)) + " |" for label, row in zip(CLASSES, matrix, strict=True)]
    return "\n".join([header, *rows])


def _diagnosis(c: Comparison) -> str:
    baselines = c.test.groupby("user")["baseline"].first()
    users = "\n".join(
        f"| {user} | {c.true_resting[user]:.1f} | {baseline:.1f} | {baseline - c.true_resting[user]:+.1f} |"
        for user, baseline in baselines.items()
    )
    deltas = c.test.groupby("label")["heart_rate_delta"].median().reindex(CLASSES)
    delta_rows = "\n".join(f"| {label} | {value:+.1f} |" for label, value in deltas.items())
    return f"""
## Diagnosis

Baseline per test user (bpm):

| User | True resting | Calibrated | Error |
|---|---|---|---|
{users}

Median heart rate above the calibrated baseline, by true level (bpm):

| True level | Median delta |
|---|---|
{delta_rows}
"""


def _reading(c: Comparison) -> str:
    return f"""
## Reading these numbers

- **The single 2-minute calibration is fragile.** It records whatever state the person is in at
  that moment. When it lands on an engaged or strained minute, the baseline is several bpm too high
  and every later window shifts down one level. With the true resting rate the same rules reach
  {c.rules_true_baseline.accuracy:.3f} accuracy instead of {c.rules.accuracy:.3f}.
- **The remaining gap is a threshold mismatch.** The rules (5 and 12 bpm, scaled by category) were
  tuned on the scripted scenarios; this generator separates levels by 1.5 / 6 / 15 bpm.
- **The model's advantage is circular.** It is trained on users of the same generator, so it learns
  this generator's offsets and its typical calibration bias. It would not transfer to real people
  on that basis, and this was expected: the value of the model is the pipeline (training, TFLite
  export, Kotlin parity, fallback to rules), not better accuracy.
- Product consequence: calibration should be repeated or validated against later calm data before
  trusting it; see the decision log.
"""
