"""Converts the mascot SVGs into Android VectorDrawables, one drawable per layer.

Usage: python scripts/mascot_to_vector.py <folder with the 5 SVGs>

Each expression becomes three drawables so the tip can sway on its own:
``mascot_<expression>_body`` (cuerpo), ``mascot_<expression>_tip`` (punta) and
``mascot_<expression>_face`` (everything drawn after the tip). All share the 256 x 256 viewport,
so they stack exactly. Shapes are translated one to one (circles, ellipses and rects become arc
and line paths; SVG rotations and scales become groups); nothing is redrawn.
"""

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SVG = "{http://www.w3.org/2000/svg}"
OUT = Path(__file__).resolve().parents[1] / "app-wear" / "src" / "main" / "res" / "drawable"
EXPRESSIONS = {
    "reposo": "rest",
    "escuchando": "listening",
    "pensando": "thinking",
    "contenta": "happy",
    "cansada": "tired",
}
NUMBER = r"-?\d+(?:\.\d+)?"
VIEWPORT = 256
SIZE_DP = 120


def main(source: Path) -> None:
    for spanish, english in EXPRESSIONS.items():
        character = ET.parse(source / f"{spanish}.svg").getroot().find(f"{SVG}g")
        layers = {"body": [], "tip": [], "face": []}
        current = "body"
        for group in character.findall(f"{SVG}g"):
            name = group.get("id")
            if name == "punta":
                current = "tip"
            elif current == "tip":
                current = "face"
            layers[current].append(group)
        for layer, groups in layers.items():
            inner = "".join(convert_group(group) for group in groups)
            write(f"mascot_{english}_{layer}", wrap(character.get("transform", ""), inner))
        print(f"{spanish} -> mascot_{english}_{{body,tip,face}}")


def wrap(transform: str, inner: str) -> str:
    rotation = rotation_group(transform)
    content = f"{rotation[0]}{inner}{rotation[1]}"
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/mascot_to_vector.py from the mascot SVGs. Do not edit by hand. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{SIZE_DP}dp" android:height="{SIZE_DP}dp"\n'
        f'    android:viewportWidth="{VIEWPORT}" android:viewportHeight="{VIEWPORT}">\n'
        f"{content}</vector>\n"
    )


def convert_group(group: ET.Element) -> str:
    body = "".join(convert_shape(shape) for shape in group)
    return f'<group android:name="{group.get("id")}">\n{body}</group>\n'


def convert_shape(shape: ET.Element) -> str:
    tag = shape.tag.removeprefix(SVG)
    if tag == "path":
        data = shape.get("d")
    elif tag == "circle":
        data = ellipse_path(*(float(shape.get(key)) for key in ("cx", "cy", "r", "r")))
    elif tag == "ellipse":
        data = ellipse_path(*(float(shape.get(key)) for key in ("cx", "cy", "rx", "ry")))
    elif tag == "rect":
        x, y, width, height = (float(shape.get(key)) for key in ("x", "y", "width", "height"))
        data = f"M{x:g},{y:g}h{width:g}v{height:g}h{-width:g}Z"
    else:
        raise ValueError(f"unsupported SVG element: {tag}")
    opening, closing = transform_group(shape.get("transform", ""))
    return f"{opening}<path{style(shape)} android:pathData=\"{data}\"/>\n{closing}"


def ellipse_path(cx: float, cy: float, rx: float, ry: float) -> str:
    return (
        f"M{cx - rx:g},{cy:g}a{rx:g},{ry:g} 0 1,0 {2 * rx:g},0"
        f"a{rx:g},{ry:g} 0 1,0 {-2 * rx:g},0Z"
    )


def style(shape: ET.Element) -> str:
    attributes = {
        "fill": ("android:fillColor", lambda v: v),
        "stroke": ("android:strokeColor", lambda v: v),
        "stroke-width": ("android:strokeWidth", lambda v: v),
        "stroke-linecap": ("android:strokeLineCap", lambda v: v),
        "stroke-linejoin": ("android:strokeLineJoin", lambda v: v),
    }
    parts = []
    for svg_name, (android_name, convert) in attributes.items():
        value = shape.get(svg_name)
        if value and value != "none":
            parts.append(f' {android_name}="{convert(value)}"')
    return "".join(parts)


def rotation_group(transform: str) -> tuple[str, str]:
    match = re.fullmatch(rf"rotate\(({NUMBER}) ({NUMBER}) ({NUMBER})\)", transform.strip())
    if not match or float(match.group(1)) == 0:
        return "", ""
    angle, x, y = match.groups()
    return f'<group android:rotation="{angle}" android:pivotX="{x}" android:pivotY="{y}">\n', "</group>\n"


def transform_group(transform: str) -> tuple[str, str]:
    """Supports ``rotate(a x y)`` and ``translate(x y) rotate(a) scale(sx sy) translate(-x -y)``."""
    if not transform:
        return "", ""
    pivoted = re.fullmatch(
        rf"translate\(({NUMBER}) ({NUMBER})\) rotate\(({NUMBER})\) scale\(({NUMBER}) ({NUMBER})\) "
        rf"translate\(-?{NUMBER} -?{NUMBER}\)",
        transform.strip(),
    )
    if pivoted:
        x, y, angle, scale_x, scale_y = pivoted.groups()
        return (
            f'<group android:pivotX="{x}" android:pivotY="{y}" android:rotation="{angle}" '
            f'android:scaleX="{scale_x}" android:scaleY="{scale_y}">\n',
            "</group>\n",
        )
    return rotation_group(transform)


def write(name: str, content: str) -> None:
    (OUT / f"{name}.xml").write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
